// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package ch10;

public interface NOTUSEOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ch10.NOTUSE)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 a = 1;</code>
   */
  int getA();
}
