// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package ch10;

public interface StreamReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ch10.StreamReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string req_info = 1;</code>
   */
  java.lang.String getReqInfo();
  /**
   * <code>string req_info = 1;</code>
   */
  com.google.protobuf.ByteString
      getReqInfoBytes();
}
