// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package ch10;

public interface StreamRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ch10.StreamResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string resp_info = 1;</code>
   */
  java.lang.String getRespInfo();
  /**
   * <code>string resp_info = 1;</code>
   */
  com.google.protobuf.ByteString
      getRespInfoBytes();
}
