// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package ch10;

public interface StudentRespListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ch10.StudentRespList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .ch10.StudentResp studentRespList = 1;</code>
   */
  java.util.List<ch10.StudentResp> 
      getStudentRespListList();
  /**
   * <code>repeated .ch10.StudentResp studentRespList = 1;</code>
   */
  ch10.StudentResp getStudentRespList(int index);
  /**
   * <code>repeated .ch10.StudentResp studentRespList = 1;</code>
   */
  int getStudentRespListCount();
  /**
   * <code>repeated .ch10.StudentResp studentRespList = 1;</code>
   */
  java.util.List<? extends ch10.StudentRespOrBuilder> 
      getStudentRespListOrBuilderList();
  /**
   * <code>repeated .ch10.StudentResp studentRespList = 1;</code>
   */
  ch10.StudentRespOrBuilder getStudentRespListOrBuilder(
      int index);
}
