// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package ch10;

/**
 * Protobuf type {@code ch10.StudentRespList}
 */
public  final class StudentRespList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ch10.StudentRespList)
    StudentRespListOrBuilder {
  // Use StudentRespList.newBuilder() to construct.
  private StudentRespList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StudentRespList() {
    studentRespList_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private StudentRespList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              studentRespList_ = new java.util.ArrayList<ch10.StudentResp>();
              mutable_bitField0_ |= 0x00000001;
            }
            studentRespList_.add(
                input.readMessage(ch10.StudentResp.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        studentRespList_ = java.util.Collections.unmodifiableList(studentRespList_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ch10.StudentProto.internal_static_ch10_StudentRespList_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ch10.StudentProto.internal_static_ch10_StudentRespList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ch10.StudentRespList.class, ch10.StudentRespList.Builder.class);
  }

  public static final int STUDENTRESPLIST_FIELD_NUMBER = 1;
  private java.util.List<ch10.StudentResp> studentRespList_;
  /**
   * <code>repeated .ch10.StudentResp studentRespList = 1;</code>
   */
  public java.util.List<ch10.StudentResp> getStudentRespListList() {
    return studentRespList_;
  }
  /**
   * <code>repeated .ch10.StudentResp studentRespList = 1;</code>
   */
  public java.util.List<? extends ch10.StudentRespOrBuilder> 
      getStudentRespListOrBuilderList() {
    return studentRespList_;
  }
  /**
   * <code>repeated .ch10.StudentResp studentRespList = 1;</code>
   */
  public int getStudentRespListCount() {
    return studentRespList_.size();
  }
  /**
   * <code>repeated .ch10.StudentResp studentRespList = 1;</code>
   */
  public ch10.StudentResp getStudentRespList(int index) {
    return studentRespList_.get(index);
  }
  /**
   * <code>repeated .ch10.StudentResp studentRespList = 1;</code>
   */
  public ch10.StudentRespOrBuilder getStudentRespListOrBuilder(
      int index) {
    return studentRespList_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < studentRespList_.size(); i++) {
      output.writeMessage(1, studentRespList_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < studentRespList_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, studentRespList_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ch10.StudentRespList)) {
      return super.equals(obj);
    }
    ch10.StudentRespList other = (ch10.StudentRespList) obj;

    boolean result = true;
    result = result && getStudentRespListList()
        .equals(other.getStudentRespListList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getStudentRespListCount() > 0) {
      hash = (37 * hash) + STUDENTRESPLIST_FIELD_NUMBER;
      hash = (53 * hash) + getStudentRespListList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ch10.StudentRespList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ch10.StudentRespList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ch10.StudentRespList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ch10.StudentRespList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ch10.StudentRespList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ch10.StudentRespList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ch10.StudentRespList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ch10.StudentRespList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ch10.StudentRespList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ch10.StudentRespList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ch10.StudentRespList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ch10.StudentRespList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ch10.StudentRespList)
      ch10.StudentRespListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ch10.StudentProto.internal_static_ch10_StudentRespList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ch10.StudentProto.internal_static_ch10_StudentRespList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ch10.StudentRespList.class, ch10.StudentRespList.Builder.class);
    }

    // Construct using ch10.StudentRespList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getStudentRespListFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (studentRespListBuilder_ == null) {
        studentRespList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        studentRespListBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ch10.StudentProto.internal_static_ch10_StudentRespList_descriptor;
    }

    public ch10.StudentRespList getDefaultInstanceForType() {
      return ch10.StudentRespList.getDefaultInstance();
    }

    public ch10.StudentRespList build() {
      ch10.StudentRespList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public ch10.StudentRespList buildPartial() {
      ch10.StudentRespList result = new ch10.StudentRespList(this);
      int from_bitField0_ = bitField0_;
      if (studentRespListBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          studentRespList_ = java.util.Collections.unmodifiableList(studentRespList_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.studentRespList_ = studentRespList_;
      } else {
        result.studentRespList_ = studentRespListBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ch10.StudentRespList) {
        return mergeFrom((ch10.StudentRespList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ch10.StudentRespList other) {
      if (other == ch10.StudentRespList.getDefaultInstance()) return this;
      if (studentRespListBuilder_ == null) {
        if (!other.studentRespList_.isEmpty()) {
          if (studentRespList_.isEmpty()) {
            studentRespList_ = other.studentRespList_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureStudentRespListIsMutable();
            studentRespList_.addAll(other.studentRespList_);
          }
          onChanged();
        }
      } else {
        if (!other.studentRespList_.isEmpty()) {
          if (studentRespListBuilder_.isEmpty()) {
            studentRespListBuilder_.dispose();
            studentRespListBuilder_ = null;
            studentRespList_ = other.studentRespList_;
            bitField0_ = (bitField0_ & ~0x00000001);
            studentRespListBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getStudentRespListFieldBuilder() : null;
          } else {
            studentRespListBuilder_.addAllMessages(other.studentRespList_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ch10.StudentRespList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ch10.StudentRespList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<ch10.StudentResp> studentRespList_ =
      java.util.Collections.emptyList();
    private void ensureStudentRespListIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        studentRespList_ = new java.util.ArrayList<ch10.StudentResp>(studentRespList_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        ch10.StudentResp, ch10.StudentResp.Builder, ch10.StudentRespOrBuilder> studentRespListBuilder_;

    /**
     * <code>repeated .ch10.StudentResp studentRespList = 1;</code>
     */
    public java.util.List<ch10.StudentResp> getStudentRespListList() {
      if (studentRespListBuilder_ == null) {
        return java.util.Collections.unmodifiableList(studentRespList_);
      } else {
        return studentRespListBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .ch10.StudentResp studentRespList = 1;</code>
     */
    public int getStudentRespListCount() {
      if (studentRespListBuilder_ == null) {
        return studentRespList_.size();
      } else {
        return studentRespListBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .ch10.StudentResp studentRespList = 1;</code>
     */
    public ch10.StudentResp getStudentRespList(int index) {
      if (studentRespListBuilder_ == null) {
        return studentRespList_.get(index);
      } else {
        return studentRespListBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .ch10.StudentResp studentRespList = 1;</code>
     */
    public Builder setStudentRespList(
        int index, ch10.StudentResp value) {
      if (studentRespListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStudentRespListIsMutable();
        studentRespList_.set(index, value);
        onChanged();
      } else {
        studentRespListBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ch10.StudentResp studentRespList = 1;</code>
     */
    public Builder setStudentRespList(
        int index, ch10.StudentResp.Builder builderForValue) {
      if (studentRespListBuilder_ == null) {
        ensureStudentRespListIsMutable();
        studentRespList_.set(index, builderForValue.build());
        onChanged();
      } else {
        studentRespListBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ch10.StudentResp studentRespList = 1;</code>
     */
    public Builder addStudentRespList(ch10.StudentResp value) {
      if (studentRespListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStudentRespListIsMutable();
        studentRespList_.add(value);
        onChanged();
      } else {
        studentRespListBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .ch10.StudentResp studentRespList = 1;</code>
     */
    public Builder addStudentRespList(
        int index, ch10.StudentResp value) {
      if (studentRespListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStudentRespListIsMutable();
        studentRespList_.add(index, value);
        onChanged();
      } else {
        studentRespListBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ch10.StudentResp studentRespList = 1;</code>
     */
    public Builder addStudentRespList(
        ch10.StudentResp.Builder builderForValue) {
      if (studentRespListBuilder_ == null) {
        ensureStudentRespListIsMutable();
        studentRespList_.add(builderForValue.build());
        onChanged();
      } else {
        studentRespListBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ch10.StudentResp studentRespList = 1;</code>
     */
    public Builder addStudentRespList(
        int index, ch10.StudentResp.Builder builderForValue) {
      if (studentRespListBuilder_ == null) {
        ensureStudentRespListIsMutable();
        studentRespList_.add(index, builderForValue.build());
        onChanged();
      } else {
        studentRespListBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ch10.StudentResp studentRespList = 1;</code>
     */
    public Builder addAllStudentRespList(
        java.lang.Iterable<? extends ch10.StudentResp> values) {
      if (studentRespListBuilder_ == null) {
        ensureStudentRespListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, studentRespList_);
        onChanged();
      } else {
        studentRespListBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .ch10.StudentResp studentRespList = 1;</code>
     */
    public Builder clearStudentRespList() {
      if (studentRespListBuilder_ == null) {
        studentRespList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        studentRespListBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .ch10.StudentResp studentRespList = 1;</code>
     */
    public Builder removeStudentRespList(int index) {
      if (studentRespListBuilder_ == null) {
        ensureStudentRespListIsMutable();
        studentRespList_.remove(index);
        onChanged();
      } else {
        studentRespListBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .ch10.StudentResp studentRespList = 1;</code>
     */
    public ch10.StudentResp.Builder getStudentRespListBuilder(
        int index) {
      return getStudentRespListFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .ch10.StudentResp studentRespList = 1;</code>
     */
    public ch10.StudentRespOrBuilder getStudentRespListOrBuilder(
        int index) {
      if (studentRespListBuilder_ == null) {
        return studentRespList_.get(index);  } else {
        return studentRespListBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .ch10.StudentResp studentRespList = 1;</code>
     */
    public java.util.List<? extends ch10.StudentRespOrBuilder> 
         getStudentRespListOrBuilderList() {
      if (studentRespListBuilder_ != null) {
        return studentRespListBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(studentRespList_);
      }
    }
    /**
     * <code>repeated .ch10.StudentResp studentRespList = 1;</code>
     */
    public ch10.StudentResp.Builder addStudentRespListBuilder() {
      return getStudentRespListFieldBuilder().addBuilder(
          ch10.StudentResp.getDefaultInstance());
    }
    /**
     * <code>repeated .ch10.StudentResp studentRespList = 1;</code>
     */
    public ch10.StudentResp.Builder addStudentRespListBuilder(
        int index) {
      return getStudentRespListFieldBuilder().addBuilder(
          index, ch10.StudentResp.getDefaultInstance());
    }
    /**
     * <code>repeated .ch10.StudentResp studentRespList = 1;</code>
     */
    public java.util.List<ch10.StudentResp.Builder> 
         getStudentRespListBuilderList() {
      return getStudentRespListFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        ch10.StudentResp, ch10.StudentResp.Builder, ch10.StudentRespOrBuilder> 
        getStudentRespListFieldBuilder() {
      if (studentRespListBuilder_ == null) {
        studentRespListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            ch10.StudentResp, ch10.StudentResp.Builder, ch10.StudentRespOrBuilder>(
                studentRespList_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        studentRespList_ = null;
      }
      return studentRespListBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:ch10.StudentRespList)
  }

  // @@protoc_insertion_point(class_scope:ch10.StudentRespList)
  private static final ch10.StudentRespList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ch10.StudentRespList();
  }

  public static ch10.StudentRespList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StudentRespList>
      PARSER = new com.google.protobuf.AbstractParser<StudentRespList>() {
    public StudentRespList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new StudentRespList(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<StudentRespList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StudentRespList> getParserForType() {
    return PARSER;
  }

  public ch10.StudentRespList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

