// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package ch10;

public interface StudentReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ch10.StudentReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 age = 1;</code>
   */
  int getAge();
}
